require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'


platform :ios, '9.0'

target 'LazerpayReactNativeExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper' => '0.80.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end
